<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {api,warehouseLabel} from '../lib/api'
const boot=ref<any>(), rows=ref<any[]>([]), error=ref(''), busy=ref(false), total=ref(0), start=ref(0), pageLength=50
const filters=ref<any>({search:'',warehouse:'',item_group:'',expiry_from:'',expiry_to:'',sort:'asc'})
async function load(){busy.value=true;error.value='';try{const d=await api('expiring_batches', {...filters.value, start:start.value, page_length:pageLength});rows.value=d.results; total.value=d.total || 0}catch(e:any){error.value=e.message}finally{busy.value=false}}
function nextPage(delta:number){ start.value=Math.max(0,start.value+delta*pageLength); void load() }
function days(n:number){return n<0?`${n} 天`:n===0?'今天到期':`还有 ${n} 天`}
onMounted(async()=>{boot.value=await api('bootstrap');await load()})
</script>
<template><main class="app-shell"><header><RouterLink to="/">‹ 首页</RouterLink><h1>有效期</h1></header><p v-if="error" class="error">{{error}}</p><form @submit.prevent="load"><input v-model="filters.search" placeholder="搜索物品或批次"><div class="form-grid"><label>仓库 / 位置<select v-model="filters.warehouse"><option value="">全部</option><option v-for="w in boot?.physical_tree||[]" :value="w.name">{{warehouseLabel(w.name,boot.warehouse_tree)}}</option></select></label><label>物品类别<select v-model="filters.item_group"><option value="">全部</option><option v-for="g in boot?.item_groups||[]" :value="g.name">{{g.item_group_name}}</option></select></label><label>到期从<input type="date" v-model="filters.expiry_from"></label><label>到期至<input type="date" v-model="filters.expiry_to"></label><label>排序<select v-model="filters.sort"><option value="asc">最近到期优先</option><option value="desc">最晚到期优先</option></select></label></div><button class="primary">应用筛选</button></form><p v-if="busy">正在加载…</p><article v-for="r in rows" :key="r.batch_no" class="item-card"><div><b>{{r.item_code}} · {{r.item_name}}</b><p>{{r.item_group}} · 批次 {{r.batch_no}} · {{r.total_qty}} {{r.stock_uom}}</p><p>到期 {{r.expiry_date}} · <span :class="{warn:r.days_to_expiry<0}">{{days(r.days_to_expiry)}}</span></p><details><summary>查看位置</summary><p v-for="l in r.locations">{{warehouseLabel(l.warehouse,boot.warehouse_tree)}} · {{l.qty}} {{r.stock_uom}}</p></details></div></article><p v-if="!busy&&!rows.length" class="empty-state">暂无有库存的有效期批次</p><nav v-if="total>pageLength" class="pagination" aria-label="有效期分页"><button type="button" :disabled="start===0" @click="nextPage(-1)">上一页</button><span>{{start+1}}–{{Math.min(start+pageLength,total)}} / {{total}}</span><button type="button" :disabled="start+pageLength>=total" @click="nextPage(1)">下一页</button></nav></main></template>