<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, warehouseLabel } from '../lib/api'
import ResponsiveFilterPanel from '../components/ResponsiveFilterPanel.vue'; import WarehouseTreeFilter from '../components/WarehouseTreeFilter.vue'; import ActiveFilterChips from '../components/ActiveFilterChips.vue'; import LoadingIndicator from '../components/LoadingIndicator.vue'
const route=useRoute(), router=useRouter(), boot=ref<any>(), rows=ref<any[]>([]), error=ref(''), busy=ref(false), total=ref(0), start=ref(0), pageLength=50, filterOpen=ref(false)
const filters=ref({search:'',warehouses:[] as string[],item_groups:[] as string[],expiry_from:'',expiry_to:'',sort:'asc'})
const activeCount=computed(()=>filters.value.warehouses.length+filters.value.item_groups.length+(filters.value.search?1:0)+(filters.value.expiry_from?1:0)+(filters.value.expiry_to?1:0)); const chips=computed(()=>[...filters.value.warehouses.map(value=>({key:'warehouses',value,label:warehouseLabel(value,boot.value?.warehouse_tree||[])})),...filters.value.item_groups.map(value=>({key:'item_groups',value,label:boot.value?.item_groups?.find((g:any)=>g.name===value)?.item_group_name||value})),...(filters.value.search?[{key:'search',label:`搜索：${filters.value.search}`}]:[]),...(filters.value.expiry_from?[{key:'expiry_from',label:`起始：${filters.value.expiry_from}`}]:[]),...(filters.value.expiry_to?[{key:'expiry_to',label:`截止：${filters.value.expiry_to}`}]:[])])
function removeChip(chip:any){if(chip.key==='warehouses')filters.value.warehouses=filters.value.warehouses.filter(v=>v!==chip.value);else if(chip.key==='item_groups')filters.value.item_groups=filters.value.item_groups.filter(v=>v!==chip.value);else (filters.value as any)[chip.key]=''} function clearAll(){filters.value={search:'',warehouses:[],item_groups:[],expiry_from:'',expiry_to:'',sort:'asc'};start.value=0}
let timer:number|undefined; async function load(){if(!boot.value)return;if(timer)window.clearTimeout(timer);timer=window.setTimeout(async()=>{busy.value=true;error.value='';try{const d=await api('expiring_batches',{...filters.value,warehouses:filters.value.warehouses.length?filters.value.warehouses:undefined,item_groups:filters.value.item_groups.length?filters.value.item_groups:undefined,start:start.value,page_length:pageLength});rows.value=d.results||[];total.value=d.total||0;void router.replace({query:{...route.query,...Object.fromEntries(Object.entries(filters.value).filter(([,v])=>Array.isArray(v)?v.length:v))}})}catch(e:any){error.value=e.message}finally{busy.value=false}},filters.value.search?300:0)}
function days(n:number){return n<0?`${n} 天`:n===0?'今天到期':`还有 ${n} 天`} function next(delta:number){start.value=Math.max(0,start.value+delta*pageLength);load()}
watch(filters,()=>{start.value=0;load()},{deep:true});onMounted(async()=>{try{boot.value=await api('bootstrap');await load()}catch(e:any){error.value=e.message}})
</script>
<template><main class="app-shell wide-shell"><header><RouterLink to="/">‹ 首页</RouterLink><h1>有效期</h1></header><p v-if="error" class="error">{{error}}</p><div class="list-layout"><ResponsiveFilterPanel v-model:open="filterOpen" :count="activeCount"><WarehouseTreeFilter v-model="filters.warehouses" :options="boot?.physical_tree||[]" :tree="boot?.warehouse_tree||[]"/><fieldset class="category-filter"><legend>物品类别</legend><label v-for="g in boot?.item_groups||[]" :key="g.name"><input v-model="filters.item_groups" type="checkbox" :value="g.name">{{g.item_group_name}}</label></fieldset><fieldset><legend>到期日期</legend><label>到期从<input v-model="filters.expiry_from" type="date"></label><label>到期至<input v-model="filters.expiry_to" type="date"></label></fieldset><fieldset><legend>排序</legend><label><input v-model="filters.sort" type="radio" value="asc">最近到期优先</label><label><input v-model="filters.sort" type="radio" value="desc">最晚到期优先</label></fieldset></ResponsiveFilterPanel><div class="results-column"><div class="result-toolbar"><input v-model="filters.search" type="search" placeholder="搜索物品或批次"><button class="mobile-filter-button" @click="filterOpen=true">筛选<span v-if="activeCount">（{{activeCount}}）</span></button><span>{{total}} 条结果</span></div><ActiveFilterChips :chips="chips" @remove="removeChip" @clear="clearAll"/><LoadingIndicator v-if="busy" text="正在加载有效期…"/><template v-else><div class="inventory-table-wrap"><table class="inventory-table"><thead><tr><th>物品 / 批次</th><th>类别</th><th>到期日期</th><th>剩余</th><th>数量</th><th>位置</th></tr></thead><tbody><tr v-for="r in rows" :key="r.batch_no"><td><b>{{r.item_name}}</b><small>{{r.item_code}} · {{r.batch_no}}</small></td><td>{{r.item_group}}</td><td>{{r.expiry_date}}</td><td :class="{warn:r.days_to_expiry<0}">{{days(r.days_to_expiry)}}</td><td class="quantity">{{r.total_qty}} {{r.stock_uom}}</td><td><span v-for="l in r.locations" :key="l.warehouse" class="location-line">{{warehouseLabel(l.warehouse,boot.warehouse_tree)}}：{{l.qty}}</span></td></tr></tbody></table></div><div class="mobile-cards"><article v-for="r in rows" :key="r.batch_no" class="item-card"><div><b>{{r.item_code}} · {{r.item_name}}</b><p>{{r.item_group}} · 批次 {{r.batch_no}} · {{r.total_qty}} {{r.stock_uom}}</p><p>到期 {{r.expiry_date}} · <span :class="{warn:r.days_to_expiry<0}">{{days(r.days_to_expiry)}}</span></p></div></article></div><p v-if="!rows.length" class="empty-state">暂无有库存的有效期批次</p></template><nav v-if="total>pageLength" class="pagination" aria-label="有效期分页"><button :disabled="start===0" @click="next(-1)">上一页</button><span>{{start+1}}–{{Math.min(start+pageLength,total)}} / {{total}}</span><button :disabled="start+pageLength>=total" @click="next(1)">下一页</button></nav></div></div></main></template>
