<script setup lang="ts">
import {ref,onMounted,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,workspaceApi,labels,warehouseLabel} from '../lib/api'
import LoadingIndicator from '../components/LoadingIndicator.vue'
const route=useRoute(),router=useRouter()
const boot=ref<any>(),rows=ref<any[]>([]),total=ref(0),unfinishedCount=ref(0),start=ref(0),error=ref(''),busy=ref(true),activities=ref<any[]>([])
const statusGroup=ref(route.query.status==='unfinished'?'unfinished':'completed')
const filters=ref<any>({search:"",movement_kind:"",date_from:"",date_to:"",source_text:"",purpose_text:"",activity:"",handler_name:"",room:""})
const activityTypeLabel=(t:string)=>({Distribution:'分发',Event:'活动',Performance:'演出','Religious Activity':'宗教活动',Maintenance:'维护',Other:'其他'} as any)[t]||t
async function load(offset=0){busy.value=true;error.value='';try{const d=await workspaceApi('history',{filters:filters.value,start:offset,status_group:statusGroup.value});rows.value=d.results;total.value=d.total;unfinishedCount.value=d.unfinished_count||0;start.value=offset}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function selectGroup(group:string){statusGroup.value=group;await router.replace({query:group==='unfinished'?{status:'unfinished'}:{}});await load()}
async function deleteDraft(name:string){if(!window.confirm('确定删除这条未完成记录吗？此操作无法撤销。'))return;try{await workspaceApi('delete_draft',{name});await load(start.value)}catch(e:any){error.value=e.message}}
watch(() => route.query.status, status => { const next = status === 'unfinished' ? 'unfinished' : 'completed'; if (next !== statusGroup.value) { statusGroup.value = next; void load() } })
onMounted(async()=>{try{boot.value=await api('bootstrap');activities.value=await workspaceApi('activities');await load()}catch(e:any){error.value=e.message}})
</script>
<template><main class="app-shell"><header><RouterLink to="/">‹ 首页</RouterLink><h1>{{statusGroup==='unfinished'?'未完成记录':'库存记录'}}</h1></header><nav class="toolbar"><button :class="{primary:statusGroup==='completed'}" @click="selectGroup('completed')">库存记录</button><button :class="{primary:statusGroup==='unfinished'}" @click="selectGroup('unfinished')">未完成记录 <b v-if="unfinishedCount">{{unfinishedCount}}</b></button></nav><p v-if="error" class="error">{{error}}</p><form @submit.prevent="load()"><input v-model="filters.search" placeholder="搜索记录、来源、物品…"><div class="form-grid"><label>交易类型<select v-model="filters.movement_kind"><option value="">全部</option><option v-for="(label,kind) in labels" :value="kind">{{label}}</option></select></label><label>开始日期<input type="date" v-model="filters.date_from"></label><label>结束日期<input type="date" v-model="filters.date_to"></label></div><details><summary>更多筛选</summary><div class="form-grid"><label>来源<input v-model="filters.source_text"></label><label>用途<input v-model="filters.purpose_text"></label><label>活动<select v-model="filters.activity"><option value="">全部</option><option v-for="a in activities" :value="a.name">{{a.title}}（{{activityTypeLabel(a.activity_type)}}）</option></select></label><label>经手人<input v-model="filters.handler_name" placeholder="按姓名筛选"></label><label>房间 / 位置<select v-model="filters.room"><option value="">全部</option><option v-for="w in boot?.physical_warehouses||[]" :value="w.name">{{warehouseLabel(w.name,boot.warehouse_tree)}}</option></select></label></div></details><button :disabled="busy">应用筛选</button><button type="button" @click="Object.keys(filters).forEach(k=>filters[k]='');load()">清除</button></form><LoadingIndicator v-if="busy" text="正在加载记录…" /><p v-else-if="!rows.length" class="empty-state">{{statusGroup==='unfinished'?'暂无未完成记录':'暂无库存记录'}}</p><article v-for="r in rows" :key="r.name" class="selection-row"><RouterLink :to="r.legacy?`/entry/${encodeURIComponent(r.name)}`:`/workspace/${r.name}`"><b>{{labels[r.movement_kind]}} · {{r.source_text||r.purpose_text||r.activity||r.name}}</b><p>{{r.posting_date}} · {{r.items.length}} 行 · {{r.docstatus===0?'编辑中':r.docstatus===1?'已完成':'已取消'}}</p><small>{{r.handler_name || r.responsible_person}}</small></RouterLink><button v-if="statusGroup==='unfinished'" @click="deleteDraft(r.name)">删除草稿</button></article><div class="toolbar"><button :disabled="start===0||busy" @click="load(start-30)">上一页</button><span>{{total}} 条记录</span><button :disabled="start+30>=total||busy" @click="load(start+30)">下一页</button></div></main></template>
