<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {api,workspaceApi,labels,warehouseLabel} from '../lib/api'
const boot=ref<any>(), rows=ref<any[]>([]), total=ref(0), start=ref(0), error=ref(''), busy=ref(false), activities=ref<any[]>([]), people=ref<any[]>([])
const filters=ref<any>({search:'',movement_kind:'',docstatus:'',date_from:'',date_to:'',source_type:'',donor_source:'',purpose:'',activity:'',responsible_person:'',room:''})
async function load(offset=0){busy.value=true;try{const d=await workspaceApi('history',{filters:filters.value,start:offset});rows.value=d.results;total.value=d.total;start.value=offset}catch(e:any){error.value=e.message}finally{busy.value=false}}
onMounted(async()=>{try{boot.value=await api('bootstrap');[activities.value,people.value]=await Promise.all([workspaceApi('activities'),workspaceApi('responsible_people')]);await load()}catch(e:any){error.value=e.message}})
</script>
<template><main class="app-shell"><header><RouterLink to="/">‹ 首页</RouterLink><h1>库存记录</h1></header><p v-if="error" class="error">{{error}}</p><form @submit.prevent="load()"><input v-model="filters.search" placeholder="搜索记录、捐赠人、物品…"><div class="form-grid"><label>交易类型<select v-model="filters.movement_kind"><option value="">全部</option><option v-for="(label,kind) in labels" :value="kind">{{label}}</option></select></label><label>状态<select v-model="filters.docstatus"><option value="">全部</option><option value="0">编辑中</option><option value="1">已完成</option><option value="2">已取消</option></select></label><label>开始日期<input type="date" v-model="filters.date_from"></label><label>结束日期<input type="date" v-model="filters.date_to"></label></div><details><summary>更多筛选</summary><div class="form-grid"><label>入库来源<select v-model="filters.source_type"><option value="">全部</option><option value="Donation">捐赠</option><option value="Purchase">采购</option><option value="Returned">退回</option><option value="Other">其他</option></select></label><label>捐赠人<input v-model="filters.donor_source"></label><label>用途<input v-model="filters.purpose"></label><label>活动<select v-model="filters.activity"><option value="">全部</option><option v-for="a in activities" :value="a.name">{{a.title}}</option></select></label><label>负责人<select v-model="filters.responsible_person"><option value="">全部</option><option v-for="p in people" :value="p.name">{{p.full_name||p.name}}</option></select></label><label>房间 / 位置<select v-model="filters.room"><option value="">全部</option><option v-for="w in boot?.warehouse_tree||[]" :value="w.name">{{warehouseLabel(w.name,boot.warehouse_tree)}}</option></select></label></div></details><button :disabled="busy">应用筛选</button><button type="button" @click="Object.keys(filters).forEach(k=>filters[k]='');load()">清除</button></form><p v-if="!rows.length&&!busy">暂无库存记录</p><RouterLink v-for="r in rows" :key="r.name" :to="r.legacy?`/entry/${encodeURIComponent(r.name)}`:`/workspace/${r.name}`" class="selection-row"><b>{{labels[r.movement_kind]}} · {{r.donor_source||r.activity||r.recipient||r.name}}</b><p>{{r.posting_date}} · {{r.items.length}} 行 · {{['编辑中','已完成','已取消'][r.docstatus]}}</p><small>{{r.responsible_person}}</small></RouterLink><div class="toolbar"><button :disabled="start===0||busy" @click="load(start-30)">上一页</button><span>{{total}} 条记录</span><button :disabled="start+30>=total||busy" @click="load(start+30)">下一页</button></div></main></template>
