<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'

const api = async (method: string, args: Record<string, unknown> = {}) => {
  const response = await fetch(`/api/method/temple_inventory.inventory_api.${method}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Frappe-CSRF-Token': (window as any).csrf_token || '' }, body: JSON.stringify(args) })
  const body = await response.json()
  if (!response.ok || body.exc) throw new Error(body._server_messages ? JSON.parse(body._server_messages)[0].message : body.message || '操作失败')
  return body.message
}
type Item = { item_code:string; item_name:string; item_group:string; stock_uom:string; image?:string; total_stock:number; available_stock:number; on_loan_qty:number; pending_qty:number; needs_attention:boolean }
type Line = { item_code:string; qty:number; uom?:string; warehouse?:string; from_warehouse?:string; to_warehouse?:string }
const page=ref<'home'|'inventory'|'attention'|'movement'|'scan'|'setup'|'programs'>('home')
const movementKind=ref('Receive'), items=ref<Item[]>([]), warehouses=ref<any[]>([]), groups=ref<any[]>([]), settings=ref<any>({}), programs=ref<any[]>([])
const query=ref(''), loading=ref(false), error=ref(''), notice=ref(''), lines=ref<Line[]>([]), selectedCode=ref(''), qty=ref(1), fromWarehouse=ref(''), toWarehouse=ref(''), leaseProgram=ref('')
const responsible=ref(''), recipient=ref(''), purpose=ref(''), donor=ref(''), notes=ref(''), signature=ref(''), setupCompany=ref(''), setupRoot=ref('寺院仓库'), programName=ref('')
const showNewItem=ref(false), newName=ref(''), newUom=ref('件'), newGroup=ref(''), newCode=ref(''), newImage=ref<File|undefined>(), newCategory=ref('')
const canvas=ref<HTMLCanvasElement>(); const video=ref<HTMLVideoElement>(); let drawing=false; let media:MediaStream|undefined
const leafWarehouses=computed(()=>warehouses.value.filter(w=>!w.is_group))
const selectableWarehouses=computed(()=>leafWarehouses.value.filter(w=>w.name!==settings.value.leased_warehouse))
const activeItems=computed(()=>items.value.filter(i=>!query.value||`${i.item_code} ${i.item_name}`.toLowerCase().includes(query.value.toLowerCase())))
const selectedItem=computed(()=>items.value.find(i=>i.item_code===selectedCode.value))
const labels:Record<string,string>={Receive:'入库',Issue:'出库 / 发放',Transfer:'转移',Loan:'借出',Return:'归还'}
async function load(attention=false){loading.value=true;error.value='';try{items.value=await api('inventory',{search:query.value||undefined,needs_attention:attention})}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function boot(){try{const d=await api('bootstrap');settings.value=d.settings;warehouses.value=d.warehouses;groups.value=d.item_groups;responsible.value=d.user;setupCompany.value=d.settings.company||'';await load();await loadPrograms()}catch(e:any){error.value=e.message}}
async function loadPrograms(){try{programs.value=await api('lease_programs')}catch(e:any){error.value=e.message}}
function openMovement(kind:string){movementKind.value=kind;lines.value=[];selectedCode.value='';qty.value=1;signature.value='';recipient.value='';purpose.value='';donor.value='';notes.value='';fromWarehouse.value='';toWarehouse.value=kind==='Receive'?settings.value.pending_warehouse||'':'';leaseProgram.value=settings.value.default_lease_program_warehouse||'';page.value='movement'}
function addLine(){const item=selectedItem.value;if(!item||qty.value<=0)return;const warehouse=movementKind.value==='Receive'?toWarehouse.value:fromWarehouse.value;const existing=lines.value.find(line=>line.item_code===item.item_code&&line.warehouse===warehouse);if(existing)existing.qty+=Number(qty.value);else lines.value.push({item_code:item.item_code,qty:Number(qty.value),uom:item.stock_uom,warehouse});selectedCode.value='';qty.value=1}
function itemFor(line:Line){return items.value.find(item=>item.item_code===line.item_code)}
async function beginNewItem(){showNewItem.value=true;newName.value='';newUom.value='件';newGroup.value=groups.value[0]?.name||'';newImage.value=undefined;try{newCode.value=await api('next_item_code')}catch(e:any){error.value=e.message}}
async function createCategory(){if(!newCategory.value)return;try{const d=await api('create_item_group',{name:newCategory.value});groups.value.push({name:d.name,item_group_name:d.item_group_name});newGroup.value=d.name;newCategory.value=''}catch(e:any){error.value=e.message}}
async function uploadImage(itemCode:string){if(!newImage.value)return '';const form=new FormData();form.append('file',newImage.value);form.append('doctype','Item');form.append('docname',itemCode);form.append('docfield','image');const response=await fetch('/api/method/upload_file',{method:'POST',headers:{'X-Frappe-CSRF-Token':(window as any).csrf_token||''},body:form});const data=await response.json();if(!response.ok||data.exc)throw new Error('图片上传失败');return data.message.file_url as string}
async function createNewItem(){if(!newName.value||!newUom.value||!newGroup.value)return error.value='请填写名称、单位和类别';loading.value=true;try{const d=await api('create_item',{data:JSON.stringify({item_name:newName.value,stock_uom:newUom.value,item_group:newGroup.value,item_code:newCode.value})});const image=await uploadImage(d.item_code);if(image){await api('set_item_image',{item_code:d.item_code,image})}const local:Item={item_code:d.item_code,item_name:newName.value,item_group:newGroup.value,stock_uom:newUom.value,image,total_stock:0,available_stock:0,on_loan_qty:0,pending_qty:0,needs_attention:true};items.value.push(local);selectedCode.value=d.item_code;showNewItem.value=false;notice.value=`已新建 ${d.item_code}`}catch(e:any){error.value=e.message}finally{loading.value=false}}
function point(e:PointerEvent){const r=canvas.value!.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.value!.width/r.width),y:(e.clientY-r.top)*(canvas.value!.height/r.height)}}
function begin(e:PointerEvent){drawing=true;const c=canvas.value?.getContext('2d'),p=point(e);c?.beginPath();c?.moveTo(p.x,p.y);(e.target as HTMLElement).setPointerCapture(e.pointerId)}
function draw(e:PointerEvent){if(!drawing)return;const c=canvas.value?.getContext('2d'),p=point(e);c?.lineTo(p.x,p.y);if(c){c.strokeStyle='#172033';c.lineWidth=3;c.lineCap='round';c.stroke()}}
function end(){if(drawing&&canvas.value)signature.value=canvas.value.toDataURL('image/png');drawing=false}
function clearSignature(){canvas.value?.getContext('2d')?.clearRect(0,0,canvas.value!.width,canvas.value!.height);signature.value=''}
async function saveMovement(submit:boolean){if(!lines.value.length)return error.value='请至少添加一个物品';if(submit&&!signature.value)return error.value='提交前请签名';loading.value=true;error.value='';try{const d=await api('save_movement',{data:JSON.stringify({movement_kind:movementKind.value,items:lines.value,from_warehouse:fromWarehouse.value,to_warehouse:toWarehouse.value,lease_program_warehouse:leaseProgram.value,responsible_person:responsible.value,recipient:recipient.value,purpose:purpose.value,donor_source:donor.value,notes:notes.value,signature:signature.value}),submit});notice.value=submit?`已提交 ${d.name}`:`草稿已保存 ${d.name}`;page.value='home';await load()}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function saveProgram(){if(!programName.value)return;try{await api('save_lease_program',{name:programName.value});programName.value='';await loadPrograms();await boot()}catch(e:any){error.value=e.message}}
async function lookup(code:string){try{const r=await api('scan',{value:code});if(r.item_code){selectedCode.value=r.item_code;page.value='movement'}}catch(e:any){error.value=e.message}}
async function camera(){try{media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});await nextTick();if(video.value)video.value.srcObject=media;const D=(window as any).BarcodeDetector;if(!D){error.value='此浏览器不支持自动识别，请手动输入编号。';return}const d=new D({formats:['qr_code','code_128','ean_13','upc_a']});const read=async()=>{if(!media||!video.value)return;const c=await d.detect(video.value);if(c[0]?.rawValue){stopCamera();await lookup(c[0].rawValue);return}requestAnimationFrame(read)};requestAnimationFrame(read)}catch{error.value='无法打开相机，请允许相机权限或手动输入。'}}
function stopCamera(){media?.getTracks().forEach(t=>t.stop());media=undefined}
async function initializeSetup(){loading.value=true;try{await api('setup',{company:setupCompany.value,root_warehouse_name:setupRoot.value});await boot();page.value='home';notice.value='库存结构已建立'}catch(e:any){error.value=e.message}finally{loading.value=false}}
onMounted(boot);onBeforeUnmount(stopCamera)
</script>
<template><main class="app-shell"><header><button class="brand" @click="page='home'">寺院库存</button><span v-if="notice" class="notice">{{notice}}</span></header><p v-if="error" class="error">{{error}}</p>
<section v-if="page==='home'" class="hero"><p class="eyebrow">库存与资产管理</p><h1>今天需要处理什么？</h1><h2>库存操作</h2><div class="quick-grid"><button v-for="kind in ['Receive','Issue','Transfer']" :key="kind" @click="openMovement(kind)">{{labels[kind]}}</button></div><h2>借用管理</h2><div class="quick-grid"><button @click="openMovement('Loan')">借出</button><button @click="openMovement('Return')">归还</button></div><div class="home-links"><button @click="page='inventory';load()">查看库存</button><button @click="page='attention';load(true)">待处理</button><button @click="page='scan';camera()">扫码</button><button @click="page='programs';loadPrograms()">借用项目</button><button @click="page='setup'">库存设置</button></div></section>
<section v-else-if="page==='inventory'||page==='attention'"><div class="page-title"><button @click="page='home'">‹ 返回</button><h1>{{page==='attention'?'待处理':'查看库存'}}</h1></div><input v-model="query" placeholder="搜索名称或库存编号" @keyup.enter="load(page==='attention')"><button @click="load(page==='attention')">搜索</button><article v-for="item in activeItems" :key="item.item_code" class="item-card"><img v-if="item.image" :src="item.image"><div><b>{{item.item_code}} · {{item.item_name}}</b><p>{{item.item_group}} · 可用 {{item.available_stock}} {{item.stock_uom}}　总计 {{item.total_stock}}</p><small v-if="item.on_loan_qty">借出 {{item.on_loan_qty}}</small><small v-if="item.pending_qty||item.needs_attention" class="warn"> 待处理</small></div></article></section>
<section v-else-if="page==='movement'"><div class="page-title"><button @click="page='home'">‹ 返回</button><h1>{{labels[movementKind]}}</h1></div><label v-if="movementKind!=='Receive'">默认从仓库<select v-model="fromWarehouse"><option value="">请选择</option><option v-for="w in selectableWarehouses" :key="w.name" :value="w.name">{{w.name}}</option></select></label><label v-if="movementKind==='Receive'||movementKind==='Transfer'||movementKind==='Return'">默认到仓库<select v-model="toWarehouse"><option value="">请选择</option><option v-for="w in selectableWarehouses" :key="w.name" :value="w.name">{{w.name}}</option></select></label><label v-if="movementKind==='Loan'">借用项目<select v-model="leaseProgram"><option v-for="p in programs" :key="p.name" :value="p.name">{{p.warehouse_name}}</option></select></label><div class="add-line"><select v-model="selectedCode"><option value="">选择物品</option><option v-for="item in items" :key="item.item_code" :value="item.item_code">{{item.item_code}} · {{item.item_name}}</option></select><input v-model.number="qty" type="number" min="0.01" step="any"><button @click="addLine">添加</button><button v-if="movementKind==='Receive'" @click="beginNewItem">新建物品</button></div><div v-if="selectedItem" class="selected-item"><img v-if="selectedItem.image" :src="selectedItem.image"><span>类别：{{selectedItem.item_group}}（自动带入）</span></div><div v-for="(line,index) in lines" :key="index" class="line"><b>{{line.item_code}}</b> × <input v-model.number="line.qty" type="number" min="0.01"><label>{{movementKind==='Receive'?'入库位置':'出库位置'}}<select v-model="line.warehouse"><option value="">请选择</option><option v-for="w in selectableWarehouses" :key="w.name" :value="w.name">{{w.name}}</option></select></label><small>类别：{{itemFor(line)?.item_group}}（自动带入）</small><button @click="lines.splice(index,1)">移除</button></div><label>负责人<input v-model="responsible" required></label><label v-if="movementKind==='Loan'||movementKind==='Return'">借用人<input v-model="recipient"></label><label>用途<input v-model="purpose"></label><label v-if="movementKind==='Receive'">来源 / 捐赠人<input v-model="donor"></label><label>备注<textarea v-model="notes"/></label><div class="signature"><span>手写签名（提交时必填）</span><canvas ref="canvas" width="600" height="180" @pointerdown="begin" @pointermove="draw" @pointerup="end" @pointerleave="end"></canvas><button @click="clearSignature">清除签名</button></div><div class="submit-row"><button @click="saveMovement(false)">保存草稿</button><button class="primary" :disabled="loading" @click="saveMovement(true)">签名并提交</button></div></section>
<section v-else-if="page==='programs'"><div class="page-title"><button @click="page='home'">‹ 返回</button><h1>借用项目</h1></div><p>每个项目是 Leased 下可存放物品的子仓库。</p><div class="add-line"><input v-model="programName" placeholder="例如：2026 暑期舞蹈"><button @click="saveProgram">创建项目</button></div><div v-for="p in programs" :key="p.name" class="line">{{p.warehouse_name}}</div></section>
<section v-else-if="page==='scan'"><div class="page-title"><button @click="stopCamera();page='home'">‹ 返回</button><h1>扫码</h1></div><video ref="video" autoplay playsinline></video><input placeholder="手动输入库存编号或条码" @keyup.enter="lookup(($event.target as HTMLInputElement).value)"></section>
<section v-else-if="page==='setup'"><div class="page-title"><button @click="page='home'">‹ 返回</button><h1>库存设置</h1></div><label>公司<input v-model="setupCompany"></label><label>寺院根仓库名称<input v-model="setupRoot"></label><button class="primary setup-button" :disabled="loading" @click="initializeSetup">建立库存结构</button></section>
<div v-if="showNewItem" class="modal"><section><h2>新建物品</h2><label>自动编号（可修改）<input v-model="newCode"></label><label>名称<input v-model="newName"></label><label>单位<input v-model="newUom"></label><label>类别<select v-model="newGroup"><option v-for="g in groups" :key="g.name" :value="g.name">{{g.item_group_name}}</option></select></label><div class="add-line"><input v-model="newCategory" placeholder="新类别"><button @click="createCategory">创建类别</button></div><label>图片（可选）<input type="file" accept="image/*" @change="newImage=($event.target as HTMLInputElement).files?.[0]"></label><button class="primary" @click="createNewItem">创建并添加</button><button @click="showNewItem=false">取消</button></section></div></main></template>