<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, workspaceApi, warehouseLabel } from '../lib/api'
import ItemImagePreview from '../components/ItemImagePreview.vue'
import LoadingIndicator from '../components/LoadingIndicator.vue'
import { toast } from '../lib/toast'
const route=useRoute(), router=useRouter(), item=ref<any>(), boot=ref<any>(), error=ref(''), chosen=ref(''), editing=ref(false), saving=ref(false)
const selectedImage=computed(()=>item.value?.images?.find((image:any)=>image.file_url===chosen.value)||item.value?.images?.[0])
function operation(kind:string){
  sessionStorage.setItem(`ti-seed:${kind}`, JSON.stringify({ items: [item.value?.item_code] }))
  void router.push(`/new/${kind}`)
}
async function saveEdit(){if(!item.value)return;saving.value=true;try{const value=await api('update_item',{item_code:item.value.item_code,data:{item_name:item.value.item_name,item_group:item.value.item_group,description:item.value.description,image:item.value.image,barcodes:String(item.value.barcodes||'').split(/[\n,]/).map((code:string)=>code.trim()).filter(Boolean)}});Object.assign(item.value,value,{barcodes:(value.barcodes||[]).join('\n')});editing.value=false;toast('物品资料已保存')}catch(e:any){error.value=e.message;toast(e.message,'error')}finally{saving.value=false}}
onMounted(async()=>{try{[boot.value,item.value]=await Promise.all([api('bootstrap'),workspaceApi('item_detail',{item_code:route.params.code})]);item.value.barcodes=(item.value.barcodes||[]).join('\n');chosen.value=item.value.images?.[0]?.file_url||''}catch(e:any){error.value=e.message}})
</script>
<template><section class="app-shell wide-shell"><header><button @click="router.back()">‹ 返回</button><h1>物品详情</h1><button v-if="boot?.can_edit_item" @click="editing=!editing">{{editing?'取消编辑':'编辑'}}</button></header><p v-if="error" class="error">{{error}}</p><LoadingIndicator v-if="!item&&!error" text="正在加载物品…"/><template v-else-if="item"><form v-if="editing" class="settings-detail" @submit.prevent="saveEdit"><h2>编辑物品资料</h2><label>名称<input v-model="item.item_name" required></label><label>类别<select v-model="item.item_group"><option v-for="group in boot.item_groups" :key="group.name" :value="group.name">{{group.item_group_name}}</option></select></label><label>说明<textarea v-model="item.description"/></label><label>条码（每行一个）<textarea v-model="item.barcodes"/></label><p class="field-hint">物品编号、库存单位和批次/效期设置需由管理员按 ERPNext 规则处理。</p><button class="primary" :disabled="saving">{{saving?'正在保存…':'保存资料'}}</button></form><section v-if="selectedImage" class="item-gallery"><ItemImagePreview :src="selectedImage.file_url" :alt="item.item_name"/><div class="gallery-thumbs"><button v-for="image in item.images" :key="image.file_url" :class="{selected:image.file_url===chosen}" :aria-label="`查看 ${image.file_name}`" @click="chosen=image.file_url"><img :src="image.file_url" :alt="image.file_name"></button></div></section><h2>{{item.item_name}}</h2><p>{{item.item_code}} · {{item.item_group}} · {{item.stock_uom}}</p><p>{{item.description}}</p><p>可用 {{item.available_stock}} · 总计 {{item.total_stock}} · 借出 {{item.on_loan_qty}} · 损坏 {{item.damaged_qty}} · 未定位 {{item.pending_qty}} {{item.stock_uom}}</p><div class="detail-actions"><button v-for="kind in ['Receive','Issue','Transfer','Loan','Damage']" :key="kind" @click="operation(kind)">{{({Receive:'入库',Issue:'出库',Transfer:'转移',Loan:'借出',Damage:'标记损坏'} as any)[kind]}}</button></div><h2>库存位置</h2><p v-if="!item.stock.length" class="empty-state">暂无库存位置记录</p><div v-for="stock in item.stock" :key="stock.warehouse" class="selection-row">{{warehouseLabel(stock.warehouse,boot.warehouse_tree)}} <b>{{stock.actual_qty}} {{item.stock_uom}}</b></div><details v-if="item.batches?.length"><summary>批次与有效期</summary><p v-for="batch in item.batches" :key="batch.batch_no">{{batch.batch_no}} · {{batch.expiry_date||'无有效期'}} · {{batch.qty}} {{item.stock_uom}}</p></details><details v-if="item.active_loans?.length"><summary>未结借用</summary><RouterLink v-for="loan in item.active_loans" :key="loan.loan_item" :to="`/loans/${encodeURIComponent(loan.loan)}`">{{loan.borrower||loan.loan}} · {{loan.outstanding}} {{loan.uom}}</RouterLink></details><h2 v-if="item.history?.length">最近库存变动</h2><RouterLink v-for="row in item.history" :key="row.name" class="selection-row" :to="row.legacy?`/entry/${encodeURIComponent(row.name)}`:`/workspace/${row.name}`">{{row.posting_date}} · {{row.movement_kind}}</RouterLink></template></section></template>
