<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../lib/api'
import LoadingIndicator from '../components/LoadingIndicator.vue'
const router = useRouter(), rows = ref<any[]>([]), total = ref(0), error = ref(''), loading = ref(false), mode = ref<'damaged' | 'unlocated'>('damaged')
const visible = computed(() => rows.value.filter(row => mode.value === 'damaged' ? Number(row.damaged_qty) > 0 : Number(row.pending_qty) > 0))
async function load(append = false) { loading.value = true; error.value = ''; try { const data = await api('pending', { start: append ? rows.value.length : 0, page_length: 25 }); rows.value = append ? [...rows.value, ...(data.results || []).filter((row: any) => !rows.value.some(old => old.item_code === row.item_code))] : data.results || []; total.value = Number(data.total || 0); if (!visible.value.length && mode.value === 'damaged' && rows.value.some(row => Number(row.pending_qty) > 0)) mode.value = 'unlocated' } catch (cause: any) { error.value = cause.message } finally { loading.value = false } }
function begin(row: any, kind: string) { sessionStorage.setItem(`ti-seed:${kind}`, JSON.stringify({ items: [row.item_code] })); void router.push(`/new/${kind}`) }
onMounted(() => void load())
</script>
<template><section class="app-shell wide-shell"><header><RouterLink to="/">‹ 库存</RouterLink><h1>待处理</h1></header><p>仅显示损坏或未定位的实际库存。共 {{ total }} 项。</p><nav class="inventory-modes" aria-label="待处理类型"><button type="button" :class="{ active: mode === 'damaged' }" @click="mode = 'damaged'">损坏</button><button type="button" :class="{ active: mode === 'unlocated' }" @click="mode = 'unlocated'">未定位</button></nav><p v-if="error" class="error">{{ error }} <button type="button" @click="load()">重试</button></p><LoadingIndicator v-if="loading && !rows.length" text="正在加载待处理物品…"/><article v-for="row in visible" :key="row.item_code" class="selection-row"><RouterLink :to="`/item/${encodeURIComponent(row.item_code)}`"><b>{{ row.item_name }}</b><small>损坏 {{ row.damaged_qty }} · 未定位 {{ row.pending_qty }} {{ row.stock_uom }}</small></RouterLink><div class="detail-actions"><button v-if="row.pending_qty" type="button" @click="begin(row, 'Transfer')">分配到位置</button><button v-if="row.damaged_qty" type="button" @click="begin(row, 'Repair')">修复归库</button><button v-if="row.damaged_qty" type="button" @click="begin(row, 'Disposal')">正式报废</button></div></article><p v-if="!visible.length && !error && !loading" class="empty-state">暂无{{ mode === 'damaged' ? '损坏' : '未定位' }}库存</p><button v-if="rows.length < total" type="button" :disabled="loading" @click="load(true)">{{ loading ? '正在加载…' : '加载更多' }}</button></section></template>
