<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {api,warehouseLabel} from '../lib/api'
import LoadingIndicator from '../components/LoadingIndicator.vue'
const boot=ref<any>(),error=ref(''),notice=ref(''),allowed=ref<string[]>([]),company=ref(''),root=ref('寺院仓库')
const fresh=ref({warehouse_name:'',parent_warehouse:'',warehouse_type:'Room',is_group:false})
async function load(){try{boot.value=await api('bootstrap');allowed.value=boot.value.warehouses.map((w:any)=>w.name);company.value=boot.value.settings.company;fresh.value.parent_warehouse=boot.value.settings.root_warehouse}catch(e:any){error.value=e.message}}
async function action(method:string,args:any={}){error.value='';notice.value='';try{await api(method,args);await load();notice.value='已保存'}catch(e:any){error.value=e.message}}
onMounted(load)
</script>
<template><main class="app-shell"><header><RouterLink to="/">‹ 首页</RouterLink><h1>库存设置</h1></header><p class="error" v-if="error">{{error}}</p><p v-if="notice" class="notice">{{notice}}</p><LoadingIndicator v-if="!boot && !error" text="正在加载设置…" /><template v-else-if="boot?.is_manager"><template v-if="boot.setup_required"><p>请先选择 ERPNext 公司，然后建立一次初始仓库模板。之后删除房间不会被自动恢复。</p><label>公司<select v-model="company"><option value="">请选择公司</option><option v-for="name in boot.companies" :key="name" :value="name">{{name}}</option></select></label><label>寺院根仓库名称<input v-model="root"></label><button :disabled="!company" @click="action('setup',{company,root_warehouse_name:root})">建立库存结构</button><p v-if="!boot.companies?.length"><a href="/app/company" target="_blank">先在 ERPNext 创建公司</a>，然后返回此页面。</p></template><template v-else><h2>房间与位置</h2><p>分类不会改变仓库层级或库存。只有叶子仓库可以存放物品。</p><article v-for="w in boot.warehouse_tree" class="selection-row"><b>{{warehouseLabel(w.name,boot.warehouse_tree)}} {{w.is_group?'（组）':''}}</b><select :value="w.warehouse_type||''" @change="action('configure_warehouse',{warehouse:w.name,warehouse_type:($event.target as HTMLSelectElement).value})"><option value="">未分类</option><option value="Room">房间</option><option value="Location">位置</option></select><label v-if="!w.is_group"><input type="checkbox" v-model="allowed" :value="w.name">允许库存操作</label></article><button @click="action('save_allowed_warehouses',{warehouses:allowed})">保存允许的位置</button><h2>添加房间 / 位置</h2><form @submit.prevent="action('configure_warehouse',fresh)"><label>名称<input v-model="fresh.warehouse_name" required></label><label>上级仓库<select v-model="fresh.parent_warehouse"><option v-for="w in (boot.physical_tree||boot.warehouse_tree).filter((w:any)=>w.is_group)" :value="w.name">{{w.warehouse_name}}</option></select></label><label>分类<select v-model="fresh.warehouse_type"><option value="Room">房间</option><option value="Location">位置</option></select></label><label><input type="checkbox" v-model="fresh.is_group">包含下级位置（组仓库）</label><button>创建</button></form></template><h2>批次</h2><p>{{boot.batch.enabled?'已启用批次功能':'尚未启用批次功能'}}</p><button v-if="!boot.batch.enabled" @click="action('enable_batches')">启用 ERPNext 批次功能</button></template><p v-else-if="boot">需要系统管理员权限。</p></main></template>
