<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../lib/api'
import { presentWarehouse, type WarehouseRecord } from '../lib/warehousePresenter'
import LoadingIndicator from '../components/LoadingIndicator.vue'
const route = useRoute(), router = useRouter(), detail = ref<any>(), boot = ref<any>(), error = ref(''), stockError = ref(''), movementsError = ref(''), stockLoading = ref(true), movementsLoading = ref(true)
const node = computed(() => detail.value?.warehouse || detail.value?.node || detail.value), presented = computed(() => node.value ? presentWarehouse(node.value as WarehouseRecord, detail.value?.warehouse_tree || boot.value?.warehouse_tree || []) : undefined)
const stock = computed(() => detail.value?.stock_preview || detail.value?.stock || []), movements = computed(() => detail.value?.movements || detail.value?.history || []), groups = computed(() => detail.value?.item_groups || detail.value?.groups || [])
const capabilities = computed(() => detail.value?.capabilities || detail.value?.quick_actions || {}), actionKinds = ['Receive', 'Issue', 'Transfer', 'Reconcile']
const permittedActions = computed(() => actionKinds.filter(kind => capabilities.value[kind] !== false && (capabilities.value[kind] || detail.value?.can_operate)))
const queryValue = computed(() => presented.value?.filterValue || String(route.params.warehouse))
function link(path: string) { return `${path}?${path === '/movements' ? 'rooms' : 'warehouses'}=${encodeURIComponent(queryValue.value)}` }
function operation(kind: string) { const value = presented.value?.operationValue; if (!value) return; sessionStorage.setItem(`ti-scope:${kind}`, JSON.stringify({ warehouse: value })); void router.push(kind === 'Reconcile' ? '/reconcile/new' : `/new/${kind}`) }
async function loadStock() { stockLoading.value = true; stockError.value = ''; try { detail.value = await api('warehouse_detail', { warehouse: route.params.warehouse }) } catch (cause: any) { stockError.value = cause.message } finally { stockLoading.value = false } }
async function loadMovements() { movementsLoading.value = true; movementsError.value = ''; try { if (!detail.value) detail.value = await api('warehouse_detail', { warehouse: route.params.warehouse }) } catch (cause: any) { movementsError.value = cause.message } finally { movementsLoading.value = false } }
onMounted(async () => { try { boot.value = await api('bootstrap') } catch (cause: any) { error.value = cause.message } await Promise.all([loadStock(), loadMovements()]) })
</script>
<template>
  <section class="app-shell wide-shell warehouse-detail-page"><header><button type="button" @click="router.back()">‹ 返回</button><div><h1>{{ presented?.localLabel || '仓库详情' }}</h1><p v-if="presented && presented.breadcrumb !== presented.localLabel">{{ presented.breadcrumb }}</p></div></header>
    <p v-if="error" class="error">{{ error }} <button type="button" @click="router.go(0)">重试</button></p><LoadingIndicator v-if="!detail && stockLoading" text="正在加载仓库详情…" /><template v-else-if="detail"><p v-if="presented && !presented.canOperate" class="notice">当前仓库暂时不能执行库存操作，请联系管理员检查配置。</p><section class="warehouse-detail-section"><h2>库存分类</h2><p v-if="!groups.length" class="empty-state">暂无库存分类</p><div v-else class="summary-grid"><article v-for="group in groups" :key="group.item_group || group.name"><strong>{{ group.item_group || group.name }}</strong><span v-for="quantity in (group.quantities || [{ qty: group.qty, uom: group.uom || group.stock_uom }])" :key="`${quantity.uom}-${quantity.qty}`">{{ quantity.qty }} {{ quantity.uom }}</span></article></div></section>
      <section class="warehouse-detail-section"><div class="section-heading"><h2>当前库存</h2><RouterLink :to="link('/')">查看全部库存</RouterLink></div><p v-if="stockError" class="error">{{ stockError }} <button type="button" @click="loadStock">重试</button></p><LoadingIndicator v-else-if="stockLoading" text="正在加载库存…" /><p v-else-if="!stock.length" class="empty-state">当前没有库存</p><div v-else class="detail-list"><article v-for="row in stock.slice(0, 20)" :key="row.name || `${row.item_code}-${row.warehouse}-${row.batch_no}`"><strong>{{ row.item_name || row.item_code }}</strong><span>{{ row.qty ?? row.actual_qty }} {{ row.uom || row.stock_uom }}</span><small v-if="row.batch_no">批次 {{ row.batch_no }}<template v-if="row.expiry_date"> · 到期 {{ row.expiry_date }}</template></small><small v-if="row.warehouse">{{ row.location_label || row.warehouse }}</small></article></div><p v-if="detail.stock_total != null" class="muted">共 {{ detail.stock_total }} 条记录</p></section>
      <section class="warehouse-detail-section"><div class="section-heading"><h2>最近动态</h2><RouterLink :to="link('/movements')">查看历史</RouterLink></div><p v-if="movementsError" class="error">{{ movementsError }} <button type="button" @click="loadMovements">重试</button></p><LoadingIndicator v-else-if="movementsLoading" text="正在加载动态…" /><p v-else-if="!movements.length" class="empty-state">暂无最近动态</p><div v-else class="detail-list"><article v-for="row in movements.slice(0, 10)" :key="row.name"><strong>{{ row.movement_kind || row.type || '库存变动' }}</strong><span>{{ row.item_name || row.item_code }} · {{ row.qty ?? row.quantity }} {{ row.uom || '' }}</span><small>{{ row.posting_date || row.date }}<template v-if="row.operator"> · {{ row.operator }}</template></small></article></div></section>
      <section v-if="presented?.canOperate" class="detail-actions warehouse-actions"><button v-for="kind in permittedActions" :key="kind" type="button" @click="operation(kind)">{{ ({ Receive:'入库', Issue:'出库', Transfer:'转移', Reconcile:'盘点' } as any)[kind] }}</button></section>
    </template>
  </section>
</template>
<style scoped>
.warehouse-detail-page header{align-items:flex-start;gap:14px}.warehouse-detail-page header>div{flex:1}.warehouse-detail-page header p{margin:0;color:#6b6257}.secondary-action{margin-left:auto}.warehouse-detail-section{margin:18px 0;padding:18px;background:#fff;border-radius:14px;box-shadow:0 2px 10px #1720330c}.section-heading{display:flex;align-items:center;justify-content:space-between}.section-heading h2{margin-top:0}.summary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.summary-grid article,.detail-list article{display:flex;flex-direction:column;gap:4px;padding:12px;border:1px solid #eee8db;border-radius:10px}.summary-grid span{font-variant-numeric:tabular-nums}.detail-list{display:grid;gap:8px}.detail-list article{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center}.detail-list small{grid-column:1/-1;color:#6b6257}.muted{color:#6b6257}.warehouse-actions{justify-content:flex-end}@media(max-width:620px){.warehouse-detail-section{padding:14px}.detail-list article{grid-template-columns:1fr}.warehouse-actions{flex-wrap:wrap}}
</style>
