<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../lib/api'
import { presentWarehouses, type PresentedWarehouse, type WarehouseRecord } from '../lib/warehousePresenter'
import { toast } from '../lib/toast'
import LoadingIndicator from '../components/LoadingIndicator.vue'
import FloatingActionMenu from '../components/FloatingActionMenu.vue'
const router = useRouter(), boot = ref<any>(), loading = ref(true), error = ref(''), search = ref(''), dialog = ref<'room' | 'location' | null>(null), saving = ref(false)
const form = ref({ parent: '', label: '' }), expanded = ref(new Set<string>()), list = ref<HTMLElement>(), dialogElement = ref<HTMLElement>(), rowRefs = new Map<string, HTMLElement>()
let previousFocus: HTMLElement | null = null
const rawRows = computed<WarehouseRecord[]>(() => boot.value?.physical_tree || boot.value?.warehouse_tree || [])
const rows = computed(() => presentWarehouses(rawRows.value))
const filtered = computed(() => rows.value.filter(row => !search.value.trim() || `${row.name} ${row.localLabel} ${row.breadcrumb}`.toLowerCase().includes(search.value.trim().toLowerCase())))
const roots = computed(() => filtered.value.filter(row => !row.parentName || !filtered.value.some(parent => parent.name === row.parentName)))
const visibleRows = computed(() => { const output: PresentedWarehouse[] = []; const visit = (parent: PresentedWarehouse | null, depth = 0) => { (parent ? filtered.value.filter(row => row.parentName === parent.name) : roots.value).forEach(row => { output.push({ ...row, displayDepth: Math.max(row.displayDepth, depth) }); if (expanded.value.has(row.name)) visit(row, depth + 1) }) }; visit(null); return output })
const context = computed(() => visibleRows.value.find(row => row.name === String(router.currentRoute.value.query.parent || '')) || roots.value[0])
const actions = computed(() => boot.value?.is_manager ? [{ kind: 'room', label: '添加房间' }, ...(context.value?.semanticType === 'room' ? [{ kind: 'location', label: '添加货位' }] : [])] : [])
function remember(el: Element | null | unknown, name: string) { if (el && el instanceof HTMLElement) rowRefs.set(name, el) }
function toggle(row: PresentedWarehouse) { const next = new Set(expanded.value); next.has(row.name) ? next.delete(row.name) : next.add(row.name); expanded.value = next }
function open(row: PresentedWarehouse) { void router.push(`/warehouses/${encodeURIComponent(row.name)}`) }
async function start(kind: string) { previousFocus = document.activeElement as HTMLElement; form.value = { parent: kind === 'location' ? (context.value?.logicalRoom || context.value?.name || '') : (context.value?.name || ''), label: '' }; dialog.value = kind as 'room' | 'location'; await nextTick(); dialogElement.value?.querySelector<HTMLElement>('input')?.focus() }
function closeDialog() { dialog.value = null; void nextTick(() => previousFocus?.focus()) }
function onDialogKeydown(event: KeyboardEvent) { if (!dialog.value) return; if (event.key === 'Escape') { event.preventDefault(); closeDialog(); return } if (event.key !== 'Tab') return; const focusable = Array.from(dialogElement.value?.querySelectorAll<HTMLElement>('button, input, [href], select, textarea') || []).filter(element => !element.hasAttribute('disabled')); if (!focusable.length) return; const index = focusable.indexOf(document.activeElement as HTMLElement); const next = event.shiftKey ? (index <= 0 ? focusable.length - 1 : index - 1) : (index === focusable.length - 1 ? 0 : index + 1); event.preventDefault(); focusable[next].focus() }
async function load() { loading.value = true; error.value = ''; try { boot.value = await api('warehouse_management_bootstrap'); rows.value.forEach(row => expanded.value.add(row.name)) } catch (cause: any) { error.value = cause.message } finally { loading.value = false } }
async function save() { if (saving.value || !form.value.label.trim() || !form.value.parent) return; saving.value = true; const kind = dialog.value; try { const result = await api(kind === 'room' ? 'create_room' : 'create_location', { parent: form.value.parent, label: form.value.label.trim() }); const parent = form.value.parent; closeDialog(); toast(kind === 'room' ? '房间已添加' : '货位已添加'); await load(); expanded.value.add(parent); await nextTick(); const created = result?.logical_room || result?.logical_node || result?.room || result?.name; if (created) rowRefs.get(created)?.focus() } catch (cause: any) { error.value = cause.message; toast(cause.message, 'error') } finally { saving.value = false } }
onMounted(() => { void load(); window.addEventListener('beforeunload', () => sessionStorage.setItem('ti-warehouse-scroll', String(list.value?.scrollTop || 0))); window.addEventListener('keydown', onDialogKeydown) })
onBeforeUnmount(() => window.removeEventListener('keydown', onDialogKeydown))
</script>
<template>
  <section class="app-shell wide-shell warehouse-page"><header><h1>仓库</h1><label class="warehouse-search">搜索仓库<input v-model="search" type="search" placeholder="搜索房间或货位" aria-label="搜索房间或货位"></label></header>
    <LoadingIndicator v-if="loading" text="正在加载仓库…" /><template v-else><p v-if="error" class="error" role="alert">{{ error }} <button type="button" @click="load">重试</button></p><p v-if="!error && !visibleRows.length" class="empty-state">暂无可查看的仓库。</p><div v-else ref="list" class="warehouse-list" tabindex="-1" role="tree" aria-label="仓库层级"><div v-for="row in visibleRows" :key="row.name" :ref="el => remember(el, row.name)" class="warehouse-row" role="treeitem" :aria-level="row.displayDepth + 1" :style="{ paddingInlineStart: `${12 + row.displayDepth * 24}px` }"><button v-if="filtered.some(child => child.parentName === row.name)" type="button" class="warehouse-disclosure" :aria-expanded="expanded.has(row.name)" :aria-label="`${expanded.has(row.name) ? '收起' : '展开'} ${row.localLabel}`" @click.stop="toggle(row)">{{ expanded.has(row.name) ? '−' : '+' }}</button><span v-else class="warehouse-disclosure" aria-hidden="true"></span><button type="button" class="warehouse-row-main" @click="open(row)"><span>{{ row.localLabel }}</span><small v-if="row.breadcrumb !== row.localLabel">{{ row.breadcrumb }}</small></button><span v-if="!row.canOperate && row.semanticType === 'room'" class="warehouse-status">暂不可操作</span></div></div><FloatingActionMenu v-if="actions.length" label="添加仓库位置" :actions="actions" @select="start" /></template>
    <div v-if="dialog" class="drawer-backdrop" role="presentation"><section ref="dialogElement" class="drawer warehouse-dialog" role="dialog" aria-modal="true" :aria-label="dialog === 'room' ? '添加房间' : '添加货位'"><form @submit.prevent="save"><h2>{{ dialog === 'room' ? '添加房间' : '添加货位' }}</h2><p>上级：{{ presentWarehouses(rawRows).find(row => row.name === form.parent)?.localLabel || form.parent }}</p><p v-if="dialog === 'room'">物品可以直接放在房间内，也可以之后再命名货位。</p><label>{{ dialog === 'room' ? '房间名称' : '货位名称' }}<input v-model="form.label" required></label><div class="detail-actions"><button class="primary" :disabled="saving">{{ saving ? '正在保存…' : '保存' }}</button><button type="button" @click="closeDialog">取消</button></div></form></section></div>
  </section>
</template>
<style scoped>
.warehouse-page header{align-items:center;gap:18px}.warehouse-search{display:flex;align-items:center;gap:8px;margin-left:auto}.warehouse-search input{margin:0;min-width:220px}.warehouse-list{overflow:auto;max-height:70dvh;background:#fff;border-radius:14px;box-shadow:0 2px 10px #1720330c}.warehouse-row{display:flex;align-items:center;gap:6px;min-height:58px;border-bottom:1px solid #eee8db}.warehouse-row-main{display:flex;flex:1;flex-direction:column;align-items:flex-start;gap:2px;min-height:44px;padding:8px;border:0;background:transparent;text-align:left}.warehouse-row-main small{color:#6b6257;font-size:12px}.warehouse-disclosure{width:32px;min-width:32px;padding:6px;border:0;background:transparent}.warehouse-status{color:#805022;font-size:12px;margin-right:12px}.warehouse-dialog{max-width:460px;margin:auto}.warehouse-dialog form{display:grid;gap:12px}@media(max-width:620px){.warehouse-page header{display:block}.warehouse-search{margin-top:12px}.warehouse-search input{min-width:0;width:100%}.warehouse-list{max-height:none}.warehouse-dialog{margin:0 12px}.warehouse-row{min-height:64px}}
</style>
