import { createRouter, createWebHistory } from 'vue-router'
export const router = createRouter({ history: createWebHistory('/inventory'), routes: [
  { path: '/', component: () => import('./pages/Inventory.vue') },
	{ path: '/adjustments', component: () => import('./pages/History.vue'), props: { destination: 'adjustments' } },
	{ path: '/loans', component: () => import('./pages/Loans.vue') },
	{ path: '/loans/:name', component: () => import('./pages/LoanDetail.vue') },
	{ path: '/warehouses', component: () => import('./pages/Warehouses.vue') },
	{ path: '/warehouses/:warehouse', component: () => import('./pages/WarehouseDetail.vue') },
	{ path: '/more', component: () => import('./pages/More.vue') },
	{ path: '/pending', component: () => import('./pages/Pending.vue') },
	{ path: '/drafts', component: () => import('./pages/History.vue'), props: { destination: 'drafts' } },
  { path: '/new/:kind', component: () => import('./pages/Workspace.vue') },
  { path: '/reconcile/new', component: () => import('./pages/Reconciliation.vue') },
  { path: '/reconcile/:name', component: () => import('./pages/Reconciliation.vue') },
  { path: '/workspace/:name', component: () => import('./pages/Workspace.vue') },
  { path: '/entry/:entry', component: () => import('./pages/Workspace.vue') },
	{ path: '/settings', redirect: '/warehouses' },
	{ path: '/history', redirect: to => to.query.status === 'unfinished' ? { path: '/drafts', query: { ...to.query, status: undefined } } : { path: '/movements', query: { ...to.query, kind: to.query.kind || to.query.movement_kind, movement_kind: undefined } } },
	{ path: '/movements', component: () => import('./pages/History.vue'), props: { destination: 'movements' } },
  { path: '/expiry', component: () => import('./pages/Expiry.vue') },
  { path: '/item/:code', component: () => import('./pages/ItemDetail.vue') },
  { path: '/auth-complete', component: { template: '<main class="app-shell"><h1>登录成功</h1><p>请返回原窗口并点击「继续保存」。</p></main>' } },
  { path: '/:pathMatch(.*)*', redirect: '/' },
] })
